/*
  This file is automatically generated. Any changes will be overwritten.
  Modify app.module.ts instead.
*/
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';

import { RadzenModule } from '@radzen/angular';

import { AppRoutes } from './app.routes';
import { AppComponent, PageTitleComponent, NavigationMenuComponent } from './app.component';
export { AppComponent } from './app.component';
import { CalidadsComponent } from './calidads/calidads.component';
import { AddCalidadComponent } from './add-calidad/add-calidad.component';
import { EditCalidadComponent } from './edit-calidad/edit-calidad.component';
import { CategoriaInsumosComponent } from './categoria-insumos/categoria-insumos.component';
import { AddCategoriaInsumoComponent } from './add-categoria-insumo/add-categoria-insumo.component';
import { EditCategoriaInsumoComponent } from './edit-categoria-insumo/edit-categoria-insumo.component';
import { CategoriaComponent } from './categoria/categoria.component';
import { AddCategoriumComponent } from './add-categorium/add-categorium.component';
import { EditCategoriumComponent } from './edit-categorium/edit-categorium.component';
import { CiudadsComponent } from './ciudads/ciudads.component';
import { AddCiudadComponent } from './add-ciudad/add-ciudad.component';
import { EditCiudadComponent } from './edit-ciudad/edit-ciudad.component';
import { ComprasComponent } from './compras/compras.component';
import { AddCompraComponent } from './add-compra/add-compra.component';
import { EditCompraComponent } from './edit-compra/edit-compra.component';
import { ComprasPagosComponent } from './compras-pagos/compras-pagos.component';
import { AddComprasPagoComponent } from './add-compras-pago/add-compras-pago.component';
import { EditComprasPagoComponent } from './edit-compras-pago/edit-compras-pago.component';
import { ControlPlagasComponent } from './control-plagas/control-plagas.component';
import { AddControlPlagaComponent } from './add-control-plaga/add-control-plaga.component';
import { EditControlPlagaComponent } from './edit-control-plaga/edit-control-plaga.component';
import { CultivosComponent } from './cultivos/cultivos.component';
import { AddCultivoComponent } from './add-cultivo/add-cultivo.component';
import { EditCultivoComponent } from './edit-cultivo/edit-cultivo.component';
import { DepartamentosComponent } from './departamentos/departamentos.component';
import { AddDepartamentoComponent } from './add-departamento/add-departamento.component';
import { EditDepartamentoComponent } from './edit-departamento/edit-departamento.component';
import { DetalleCategoriaInsumosComponent } from './detalle-categoria-insumos/detalle-categoria-insumos.component';
import { AddDetalleCategoriaInsumoComponent } from './add-detalle-categoria-insumo/add-detalle-categoria-insumo.component';
import { EditDetalleCategoriaInsumoComponent } from './edit-detalle-categoria-insumo/edit-detalle-categoria-insumo.component';
import { DetalleComprasComponent } from './detalle-compras/detalle-compras.component';
import { AddDetalleCompraComponent } from './add-detalle-compra/add-detalle-compra.component';
import { EditDetalleCompraComponent } from './edit-detalle-compra/edit-detalle-compra.component';
import { DetalleMetodopagosComponent } from './detalle-metodopagos/detalle-metodopagos.component';
import { AddDetalleMetodopagoComponent } from './add-detalle-metodopago/add-detalle-metodopago.component';
import { EditDetalleMetodopagoComponent } from './edit-detalle-metodopago/edit-detalle-metodopago.component';
import { DetalleOfertaComponent } from './detalle-oferta/detalle-oferta.component';
import { AddDetalleOfertumComponent } from './add-detalle-ofertum/add-detalle-ofertum.component';
import { EditDetalleOfertumComponent } from './edit-detalle-ofertum/edit-detalle-ofertum.component';
import { DetalleTipoProductosComponent } from './detalle-tipo-productos/detalle-tipo-productos.component';
import { AddDetalleTipoProductoComponent } from './add-detalle-tipo-producto/add-detalle-tipo-producto.component';
import { EditDetalleTipoProductoComponent } from './edit-detalle-tipo-producto/edit-detalle-tipo-producto.component';
import { EnfermedadesComponent } from './enfermedades/enfermedades.component';
import { AddEnfermedadeComponent } from './add-enfermedade/add-enfermedade.component';
import { EditEnfermedadeComponent } from './edit-enfermedade/edit-enfermedade.component';
import { EquiposComponent } from './equipos/equipos.component';
import { AddEquipoComponent } from './add-equipo/add-equipo.component';
import { EditEquipoComponent } from './edit-equipo/edit-equipo.component';
import { FotosComponent } from './fotos/fotos.component';
import { AddFotoComponent } from './add-foto/add-foto.component';
import { EditFotoComponent } from './edit-foto/edit-foto.component';
import { InsumosComponent } from './insumos/insumos.component';
import { AddInsumoComponent } from './add-insumo/add-insumo.component';
import { EditInsumoComponent } from './edit-insumo/edit-insumo.component';
import { LaboratoriosComponent } from './laboratorios/laboratorios.component';
import { AddLaboratorioComponent } from './add-laboratorio/add-laboratorio.component';
import { EditLaboratorioComponent } from './edit-laboratorio/edit-laboratorio.component';
import { LocalizacionUpsComponent } from './localizacion-ups/localizacion-ups.component';
import { AddLocalizacionUpComponent } from './add-localizacion-up/add-localizacion-up.component';
import { EditLocalizacionUpComponent } from './edit-localizacion-up/edit-localizacion-up.component';
import { LotesComponent } from './lotes/lotes.component';
import { AddLoteComponent } from './add-lote/add-lote.component';
import { EditLoteComponent } from './edit-lote/edit-lote.component';
import { MetodoPagosComponent } from './metodo-pagos/metodo-pagos.component';
import { AddMetodoPagoComponent } from './add-metodo-pago/add-metodo-pago.component';
import { EditMetodoPagoComponent } from './edit-metodo-pago/edit-metodo-pago.component';
import { NotificacionesComponent } from './notificaciones/notificaciones.component';
import { AddNotificacioneComponent } from './add-notificacione/add-notificacione.component';
import { EditNotificacioneComponent } from './edit-notificacione/edit-notificacione.component';
import { OfertaComponent } from './oferta/oferta.component';
import { AddOfertaComponent } from './add-oferta/add-oferta.component';
import { EditOfertaComponent } from './edit-oferta/edit-oferta.component';
import { PagosComponent } from './pagos/pagos.component';
import { AddPagoComponent } from './add-pago/add-pago.component';
import { EditPagoComponent } from './edit-pago/edit-pago.component';
import { ProduccionsComponent } from './produccions/produccions.component';
import { AddProduccionComponent } from './add-produccion/add-produccion.component';
import { EditProduccionComponent } from './edit-produccion/edit-produccion.component';
import { ProductCategoriaComponent } from './product-categoria/product-categoria.component';
import { AddProductCategoriumComponent } from './add-product-categorium/add-product-categorium.component';
import { EditProductCategoriumComponent } from './edit-product-categorium/edit-product-categorium.component';
import { ProductosComponent } from './productos/productos.component';
import { AddProductoComponent } from './add-producto/add-producto.component';
import { EditProductoComponent } from './edit-producto/edit-producto.component';
import { RecetaComponent } from './receta/receta.component';
import { AddRecetumComponent } from './add-recetum/add-recetum.component';
import { EditRecetumComponent } from './edit-recetum/edit-recetum.component';
import { RolsComponent } from './rols/rols.component';
import { AddRolComponent } from './add-rol/add-rol.component';
import { EditRolComponent } from './edit-rol/edit-rol.component';
import { TipoInsumosComponent } from './tipo-insumos/tipo-insumos.component';
import { AddTipoInsumoComponent } from './add-tipo-insumo/add-tipo-insumo.component';
import { EditTipoInsumoComponent } from './edit-tipo-insumo/edit-tipo-insumo.component';
import { TipoProductosComponent } from './tipo-productos/tipo-productos.component';
import { AddTipoProductoComponent } from './add-tipo-producto/add-tipo-producto.component';
import { EditTipoProductoComponent } from './edit-tipo-producto/edit-tipo-producto.component';
import { TratamientosComponent } from './tratamientos/tratamientos.component';
import { AddTratamientoComponent } from './add-tratamiento/add-tratamiento.component';
import { EditTratamientoComponent } from './edit-tratamiento/edit-tratamiento.component';
import { TypeNotificationsComponent } from './type-notifications/type-notifications.component';
import { AddTypeNotificationComponent } from './add-type-notification/add-type-notification.component';
import { EditTypeNotificationComponent } from './edit-type-notification/edit-type-notification.component';
import { UnidadMedidasComponent } from './unidad-medidas/unidad-medidas.component';
import { AddUnidadMedidaComponent } from './add-unidad-medida/add-unidad-medida.component';
import { EditUnidadMedidaComponent } from './edit-unidad-medida/edit-unidad-medida.component';
import { UnidadProductivasComponent } from './unidad-productivas/unidad-productivas.component';
import { AddUnidadProductivaComponent } from './add-unidad-productiva/add-unidad-productiva.component';
import { EditUnidadProductivaComponent } from './edit-unidad-productiva/edit-unidad-productiva.component';
import { UsuariosComponent } from './usuarios/usuarios.component';
import { AddUsuarioComponent } from './add-usuario/add-usuario.component';
import { EditUsuarioComponent } from './edit-usuario/edit-usuario.component';
import { LoginComponent } from './login/login.component';
import { UsersComponent } from './users/users.component';
import { RolesComponent } from './roles/roles.component';
import { AddRoleComponent } from './add-role/add-role.component';
import { EditUserComponent } from './edit-user/edit-user.component';
import { ProfileComponent } from './profile/profile.component';
import { UnauthorizedComponent } from './unauthorized/unauthorized.component';
import { AddUserComponent } from './add-user/add-user.component';
import { RegisterUserComponent } from './register-user/register-user.component';
import { FilterComponent } from './filter/filter.component';

import { AgriculturebdService } from './agriculturebd.service';
import { SecurityService, UserService } from './security.service';
import { SecurityInterceptor } from './security.interceptor';
import { AuthGuard } from './auth.guard';

export const PageDeclarations = [
  CalidadsComponent,
  AddCalidadComponent,
  EditCalidadComponent,
  CategoriaInsumosComponent,
  AddCategoriaInsumoComponent,
  EditCategoriaInsumoComponent,
  CategoriaComponent,
  AddCategoriumComponent,
  EditCategoriumComponent,
  CiudadsComponent,
  AddCiudadComponent,
  EditCiudadComponent,
  ComprasComponent,
  AddCompraComponent,
  EditCompraComponent,
  ComprasPagosComponent,
  AddComprasPagoComponent,
  EditComprasPagoComponent,
  ControlPlagasComponent,
  AddControlPlagaComponent,
  EditControlPlagaComponent,
  CultivosComponent,
  AddCultivoComponent,
  EditCultivoComponent,
  DepartamentosComponent,
  AddDepartamentoComponent,
  EditDepartamentoComponent,
  DetalleCategoriaInsumosComponent,
  AddDetalleCategoriaInsumoComponent,
  EditDetalleCategoriaInsumoComponent,
  DetalleComprasComponent,
  AddDetalleCompraComponent,
  EditDetalleCompraComponent,
  DetalleMetodopagosComponent,
  AddDetalleMetodopagoComponent,
  EditDetalleMetodopagoComponent,
  DetalleOfertaComponent,
  AddDetalleOfertumComponent,
  EditDetalleOfertumComponent,
  DetalleTipoProductosComponent,
  AddDetalleTipoProductoComponent,
  EditDetalleTipoProductoComponent,
  EnfermedadesComponent,
  AddEnfermedadeComponent,
  EditEnfermedadeComponent,
  EquiposComponent,
  AddEquipoComponent,
  EditEquipoComponent,
  FotosComponent,
  AddFotoComponent,
  EditFotoComponent,
  InsumosComponent,
  AddInsumoComponent,
  EditInsumoComponent,
  LaboratoriosComponent,
  AddLaboratorioComponent,
  EditLaboratorioComponent,
  LocalizacionUpsComponent,
  AddLocalizacionUpComponent,
  EditLocalizacionUpComponent,
  LotesComponent,
  AddLoteComponent,
  EditLoteComponent,
  MetodoPagosComponent,
  AddMetodoPagoComponent,
  EditMetodoPagoComponent,
  NotificacionesComponent,
  AddNotificacioneComponent,
  EditNotificacioneComponent,
  OfertaComponent,
  AddOfertaComponent,
  EditOfertaComponent,
  PagosComponent,
  AddPagoComponent,
  EditPagoComponent,
  ProduccionsComponent,
  AddProduccionComponent,
  EditProduccionComponent,
  ProductCategoriaComponent,
  AddProductCategoriumComponent,
  EditProductCategoriumComponent,
  ProductosComponent,
  AddProductoComponent,
  EditProductoComponent,
  RecetaComponent,
  AddRecetumComponent,
  EditRecetumComponent,
  RolsComponent,
  AddRolComponent,
  EditRolComponent,
  TipoInsumosComponent,
  AddTipoInsumoComponent,
  EditTipoInsumoComponent,
  TipoProductosComponent,
  AddTipoProductoComponent,
  EditTipoProductoComponent,
  TratamientosComponent,
  AddTratamientoComponent,
  EditTratamientoComponent,
  TypeNotificationsComponent,
  AddTypeNotificationComponent,
  EditTypeNotificationComponent,
  UnidadMedidasComponent,
  AddUnidadMedidaComponent,
  EditUnidadMedidaComponent,
  UnidadProductivasComponent,
  AddUnidadProductivaComponent,
  EditUnidadProductivaComponent,
  UsuariosComponent,
  AddUsuarioComponent,
  EditUsuarioComponent,
  LoginComponent,
  UsersComponent,
  RolesComponent,
  AddRoleComponent,
  EditUserComponent,
  ProfileComponent,
  UnauthorizedComponent,
  AddUserComponent,
  RegisterUserComponent,
  FilterComponent,
  PageTitleComponent
];

export const AppDeclarations = [
  ...PageDeclarations,
  AppComponent,
  NavigationMenuComponent
];

export const AppProviders = [
  AgriculturebdService,
  UserService,
  SecurityService,
  {
    provide: HTTP_INTERCEPTORS,
    useClass: SecurityInterceptor,
    multi: true
  },
  AuthGuard
];

export const AppImports = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  HttpClientModule,
  RadzenModule,
  AppRoutes
];
