/*
  This file is automatically generated. Any changes will be overwritten.
  Modify filter.component.ts instead.
*/
import { ChangeDetectorRef, ViewChild, AfterViewInit, Injector, OnInit, OnDestroy } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { Location } from '@angular/common';
import { Subscription } from 'rxjs';

import { NotificationService, DialogService, DIALOG_PARAMETERS, DialogRef } from '@radzen/angular';
import { DropDownComponent } from '@radzen/angular';

import { AgriculturebdService } from '../agriculturebd.service';
import { SecurityService } from '../security.service';

export class FilterGenerated implements AfterViewInit, OnInit, OnDestroy {
  // Components
  @ViewChild(DropDownComponent) metodos: DropDownComponent;
  @ViewChild(DropDownComponent) detalles: DropDownComponent;

  router: Router;

  cd: ChangeDetectorRef;

  route: ActivatedRoute;

  notificationService: NotificationService;

  dialogService: DialogService;

  dialogRef: DialogRef;

  _location: Location;

  _subscription: Subscription;

  agriculturebd: AgriculturebdService;

  security: SecurityService;

  getMetodoPagosResult: any;

  parameters: any;

  DetalleResul: any;

  constructor(private injector: Injector) {
  }

  ngOnInit() {
    this.notificationService = this.injector.get(NotificationService);

    this.dialogService = this.injector.get(DialogService);

    this.dialogRef = this.injector.get(DialogRef, null);

    this.router = this.injector.get(Router);

    this.cd = this.injector.get(ChangeDetectorRef);

    this._location = this.injector.get(Location);

    this.route = this.injector.get(ActivatedRoute);

    this.agriculturebd = this.injector.get(AgriculturebdService);
    this.security = this.injector.get(SecurityService);
  }

  ngAfterViewInit() {
    this._subscription = this.route.params.subscribe(parameters => {
      if (this.dialogRef) {
        this.parameters = this.injector.get(DIALOG_PARAMETERS);
      } else {
        this.parameters = parameters;
      }
      this.load();
      this.cd.detectChanges();
    });
  }

  ngOnDestroy() {
    this._subscription.unsubscribe();
  }


  load() {
    this.agriculturebd.getMetodoPagos(null, null, null, null, null, null)
    .subscribe((result: any) => {
      this.getMetodoPagosResult = result.value;
    }, (result: any) => {

    });
  }

  MetodosChange(event: any) {
    this.agriculturebd.getDetalleMetodopagos(`MetodoPagoId eq ${event.Id}`, null, null, null, null, null)
    .subscribe((result: any) => {
      this.DetalleResul = result.value;
    }, (result: any) => {

    });
  }
}
